// @Constants
import { VideoData } from '../constants/types';

const videosData: Array<VideoData> = [
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '0',
    isNew: true,
    isSeries: true,
    coincidence: 60,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 0,
    posterSrc: require('../assets/png/ben_shapiro_show.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Ben Shapiro show',
    seasonsAmount: 6,
    src: require('../assets/podcasts/ben_shapiro_show.mp4'),
    year: 2019
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '1',
    isNew: false,
    isSeries: true,
    coincidence: 96,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 16,
    posterSrc: require('../assets/png/call_her_daddy.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Call her daddy',
    seasonsAmount: 0,
    src: require('../assets/podcasts/call_her_daddy.mp4'),
    year: 2018
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '2',
    isNew: false,
    isSeries: true,
    coincidence: 70,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 13,
    posterSrc: require('../assets/png/pardon_my_take.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Pardon my take',
    seasonsAmount: 2,
    src: require('../assets/podcasts/pardon_my_take.mp4'),
    year: 2016
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id:'3',
    isNew: false,
    isSeries: true,
    coincidence: 35,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 16,
    posterSrc: require('../assets/png/planet_money.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Planet money',
    seasonsAmount: 1,
    src: require('../assets/podcasts/planet_money.mp4'),
    year: 2015
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '4',
    isNew: true,
    isSeries: true,
    coincidence: 35,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 0,
    posterSrc: require('../assets/png/radiolab.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Radiolab',
    seasonsAmount: 1,
    src: require('../assets/podcasts/radiolab.mp4'),
    year: 2019
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '5',
    isNew: false,
    isSeries: true,
    coincidence: 75,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 0,
    posterSrc: require('../assets/png/stuff_you_should_know.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'Stuff you should know',
    seasonsAmount: 4,
    src: require('../assets/podcasts/stuff_you_should_know.mp4'),
    year: 2013
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '6',
    isNew: false,
    isSeries: true,
    coincidence: 20,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 0,
    posterSrc: require('../assets/png/ted_radio_hour.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'The radio hour',
    seasonsAmount: 1,
    src: require('../assets/podcasts/ted_radio_hour.mp4'),
    year: 2014
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '7',
    isNew: true,
    isSeries: true,
    coincidence: 20,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 13,
    posterSrc: require('../assets/png/the_daily.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'The daily',
    seasonsAmount: 1,
    src: require('../assets/podcasts/the_daily.mp4'),
    year: 2019
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '8',
    isNew: false,
    isSeries: true,
    coincidence: 20,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 0,
    posterSrc: require('../assets/png/this_american_life.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'The american life',
    seasonsAmount: 2,
    src: require('../assets/podcasts/this_american_life.mp4'),
    year: 2016
  },
  {
    cast: ['Cast member 1', 'Cast member 2', 'Cast member 3'],
    id: '9',
    isNew: false,
    isSeries: true,
    coincidence: 20,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius odio sit amet erat tempus tincidunt. Etiam bibendum nunc tellus, eget gravida risus placerat in. Interdum et malesuada fames ac ante ipsum primis in faucibus.',
    duration: 60000,
    genres: ['Genre 1', 'Genre 2', 'Genre 3'],
    parentalAge: 13,
    posterSrc: require('../assets/png/up_first.png'),
    tags: ['Tag 1', 'Tag 2', 'Tag 3'],
    title: 'The first',
    seasonsAmount: 3,
    src: require('../assets/podcasts/up_first.mp4'),
    year: 2016
  }
];

export default videosData;