export const PLAYER_ENABLE = 'PLAYER_ENABLE';
export const PLAYER_REQUEST_CONTROL = 'PLAYER_REQUEST_CONTROL';
export const SLIDER_OPEN_DESCRIPTIONS = 'SLIDER_OPEN_DESCRIPTIONS';
export const SLIDER_REGISTER_SLIDER = 'SLIDER_REGISTER_SLIDER';
export const SLIDER_UNREGISTER_SLIDER = 'SLIDER_UNREGISTER_SLIDER';
