export const EPISPDES_SET_EPISODE_DATA = 'EPISPDES_SET_EPISODE_DATA';
export const PLAYER_ENABLE = 'PLAYER_ENABLE';
export const PLAYER_REQUEST_CONTROL = 'PLAYER_REQUEST_CONTROL';
export const PODCAST_GET_FEATURED = 'PODCAST_GET_FEATURED';
export const PODCASTS_GET_SLIDERS_DATA = 'PODCASTS_GET_SLIDERS_DATA';
export const SLIDER_OPEN_DESCRIPTIONS = 'SLIDER_OPEN_DESCRIPTIONS';
export const SLIDER_REGISTER_SLIDER = 'SLIDER_REGISTER_SLIDER';
export const SLIDER_UNREGISTER_SLIDER = 'SLIDER_UNREGISTER_SLIDER';
